select * from emp;

SELECT * INTO TRG_EMP FROM EMP WHERE 1=2;

SELECT * FROM TRG_EMP_DEMO43;

SELECT * FROM EMP;

SELECT EMPNO,ENAME,SAL,DEPTNO,JOB INTO TRG_EMP_DEMO3 FROM EMP WHERE 1=2;

SELECT EMPNO,ENAME AS NAME,SAL AS SALARY,DEPTNO AS DNO INTO TRG_EMP_DIFF1 FROM EMP WHERE 1=2;

SELECT * FROM TRG_EMP_10;

SELECT EMPNO,ENAME AS NAME,SAL AS SALARY,DEPTNO AS DNO INTO TRG_EMP_10 FROM EMP WHERE 1=2;

SELECT EMPNO,ENAME AS NAME,SAL AS SALARY,DEPTNO AS DNO INTO TRG_EMP_20 FROM EMP WHERE 1=2;

SELECT * FROM TRG_EMP_CREATE;

select * from TRG_EMP_DEMO31;

select * into trg_dept from dept where 1=2;

CREATE TABLE TRG_DEMO_6(EMPNO INT,ENAME VARCHAR(20),SAL INT,DEPTNO INT,TAX FLOAT);

select * from TRG_DEMO_81;
CREATE TABLE TRG_DEMO_8(EMPNO INT,ENAME VARCHAR(20),SAL INT,COMM FLOAT, TSAL INT,TAX FLOAT,DEPTNO INT);


SELECT EMPNO,ENAME,SAL,DEPTNO,JOB INTO TRG_JOIN_EMP FROM EMP WHERE 1=2;

SELECT EMPNO,ENAME,SAL,DEPTNO,JOB INTO TRG_JOIN_EMP1 FROM EMP WHERE 1=2;
select * from TRG_JOIN_EMP_LEFT;

ALTER TABLE TRG_JOIN_EMP_LEFT ADD LOC VARCHAR(20);
SELECT * INTO TRG_JOIN_EMP_J1 FROM EMP WHERE 1=2;
select * from TRG_JOIN_EMP_J1;

SELECT *FROM EMP_AGGR;

SELECT * INTO EMPUNIONA FROM EMP WHERE DEPTNO=10;

SELECT * INTO EMPUNIONB FROM EMP WHERE DEPTNO=20;

SELECT DEPTNO,SUM_SAL INTO TALEND_EMP_AGGR1 FROM EMP WHERE 1=2;

SELECT *FROM EMPUNIONA;
SELECT *FROM EMPUNIONB;
SELECT *FROM EMPUNIONTRG;

CREATE TABLE AGG(DEPTNO INT, SUM_SAL INT);

SELECT * FROM TRG_EXA;

CREATE TABLE TRG_EXA(EMPNO INT,ENAME VARCHAR(20),SAL INT,COMM FLOAT,JOB VARCHAR(20),TRATE FLOAT,NETSAL INT, TSAL INT,TAX FLOAT,DEPTNO INT);

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM INTO TRG_EXB1 FROM EMP WHERE 1=2
SELECT DEPTNO,COMM,JOB INTO TRG_EXB3 FROM EMP WHERE 1=2

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_EXD1 FROM EMP WHERE 1=2

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_EXD2 FROM EMP WHERE 1=2

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_EXD3 FROM EMP WHERE 1=2

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_EXD4 FROM EMP WHERE 1=2

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_EXD5 FROM EMP WHERE 1=2



SELECT * FROM TRG_EXB3;

SELECT * FROM TRG_EXD1;
SELECT * FROM EMP;
SELECT * FROM TRG_EXD2;

SELECT * FROM TRG_EXD3;

SELECT * FROM TRG_EXD4;

SELECT * FROM TRG_EXD5;

DELETE FROM EMP WHERE DEPTNO=40

CREATE TABLE TRG_EXE1(EMPNO INT,ENAME VARCHAR(20),SAL INT,COMM FLOAT,TSAL INT,DEPTNO INT,JOB VARCHAR(20),DNAME VARCHAR(20),LOC VARCHAR(20));

CREATE TABLE TRG_EXE2(EMPNO INT,ENAME VARCHAR(20),SAL INT,COMM FLOAT,TSAL INT,DEPTNO INT,JOB VARCHAR(20),DNAME VARCHAR(20),LOC VARCHAR(20));

SELECT * FROM TRG_EXE1;

SELECT * FROM DEPT;
DELETE FROM DEPT WHERE DEPTNO=10
insert into EMP values (10,'CHENNAI');

SELECT E.DEPTNO,D.DNAME,D.LOC,E.SAL AS SUM_SAL,E.SAL AS MAX_SAL,E.SAL AS TAX_SUM_SAL INTO TRG_EXF1 FROM EMP E, DEPT D WHERE 1=2; 
SELECT * FROM TRG_EXF1;
SELECT * FROM TRG_EXF2;

SELECT * INTO TRG_SCD FROM EMP WHERE 1=2;

ALTER TABLE TRG_SCD ADD S_KEY INT, VER_NO INT, FLAG_NO BIT, START_DATES DATE, END_DATE DATE;

SELECT * FROM EMP;

SELECT * FROM TRG_SCD;

UPDATE EMP SET SAL=SAL+1000 WHERE EMPNO=7934;

SELECT EMPNO,ENAME,SAL,DEPTNO INTO TRG_EXF2 FROM EMP WHERE 1=2;

ALTER TABLE TRG_EXF3 ADD REC_ID INT;

SELECT EMPNO,ENAME,SAL,DEPTNO,EMPNO AS REC_ID INTO TRG_EXF2 FROM EMP WHERE 1=2;

ALTER TABLE TRG_EXF3 DROP COLUMN REC_ID;

DROP TABLE TRG_EXF3;

SELECT * FROM TRG_EXF2;

SELECT * FROM TRG_EXF3;